#!/bin/bash
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# This example catches duplicate Signed-off-by lines.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# test "" = "$(grep '^Signed-off-by: ' "$1" |
# 	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
# 	echo >&2 Duplicate Signed-off-by lines.
# 	exit 1
# }

# MSG_FILE=$1

# count_added=$( grep -E "^added - " ${MSG_FILE} | wc -l)
# count_added_without_comment=$( grep -E "^added - \b(.*)\b\:(\s+)?$" ${MSG_FILE} | wc -l)

# if [[ ${count_added} -gt 0 ]] && [[ ${count_added_without_comment} -gt 0 ]]; then
#     echo "There are new files added that have no commit message detailing changes"
#     TMP_FILE=~/.tmp_aborted_commit_msg
#     cat ${MSG_FILE} > ${TMP_FILE}
#     exit 1
# fi

# count_changes=$( grep -E "^modified - " ${MSG_FILE} | wc -l)
# count_changes_without_comment=$( grep -E "^modified - \b(.*)\b\:(\s+)?$" ${MSG_FILE} | wc -l)

# if [[ ${count_changes} -gt 0 ]] && [[ ${count_changes_without_comment} -gt 0 ]]; then
#     echo "There are files modified that have no commit message detailing changes"
#     TMP_FILE=~/.tmp_aborted_commit_msg
#     cat ${MSG_FILE} > ${TMP_FILE}
#     exit 1
# fi

# count_renames=$(grep -E "^renamed" ${MSG_FILE} | wc -l)
# count_renames_without_comment=$(grep -E "^renamed - \b(.*)\b\:(\s+)?$" ${MSG_FILE}| wc -l)

# if [[ ${count_renames} -gt 0 ]] && [[ ${count_renames_without_comment} -gt 0 ]]; then
#     echo "There are files renamed that have no commit message detailing renaming"
#     TMP_FILE=~/.tmp_aborted_commit_msg
#     cat ${MSG_FILE} > ${TMP_FILE}
#     exit 1
# fi
